name = "PrettyEinsum"
uuid = "32b504e2-49a9-444c-8a4e-7081de4137a2"
authors = ["Hayate Nakano <nakanodesu@gmail.com> and contributors"]
version = "0.1.0"

[deps]
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
